CREATE TABLE tb_missoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dificuldade VARCHAR(255),
    nome VARCHAR(255)
);

CREATE TABLE tb_cadastro_de_ninjas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    idade INTEGER NOT NULL,
    img_url VARCHAR(255),
    nome VARCHAR(255),
    missoes_id BIGINT,
    CONSTRAINT fk_ninjas_missoes
        FOREIGN KEY (missoes_id)
        REFERENCES tb_missoes (id)
);
